### ISSUE TITLE
Phone numbers must be exactly 10 chars without punctuation.  Primary is required.

### ISSUE THREAD

**Issue by mpmks1** [SueJStevens/KoolSkool#22]
1. Create new sql seeds files for parents and personnel which strips punctuation from phone fields.  All phone numbers should now be 10 chars.
2. Modify models for parents and personnel to reflect primary number required and length must validate to 10 chars
3. Modify data entry forms for parents and personnel to require primary number.
4. Modify data entry forms to strip punctuation prior to sending data to sequelize validation.

**Comment by SueJStevens** [comment]
Should be fixed with the latest pull request.
